services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dikmen-backend
    working_dir: /var/www/html
    volumes:
      - backend-data:/var/www/html/storage
    ports:
      - "8000:80"
    env_file: .env
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PASSWORD=password
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_DATABASE=blobartdesign
      - DB_USERNAME=root
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: blobartdesign-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dikmen
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
#      - ./backend/blobartdesign.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dikmen-phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:
  backend-data:


networks:
  app-network:
    driver: bridge


  # networks:
  #   blobartdesign-network

  # Nginx web server
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: unless-stopped
  #   volumes:
  #     - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./frontend:/frontend  # Mount the frontend code
  #     - ./backend:/backend  # Mount the backend code
  #   ports:
  #     - "8010:8010"
  #   depends_on:
  #     - laravel
  #     - next-app
